server:
  tomcat:
    max-http-form-post-size: 110MB
  timezone: Asia/Seoul
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://caringnote.co.kr/keycloak/realms/caringnote
          jwk-set-uri: https://caringnote.co.kr/keycloak/realms/caringnote/protocol/openid-connect/certs
  config:
    import: optional:application-secret.yml
  docker:
    compose:
      enabled: false
      lifecycle-management:
        readiness-checks-enabled: false
  application:
    name: api
  profiles:
    active: local
  doc:
    api-docs:
      path: /v1/api-docs
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      accept-empty-string-as-null-object: true
      read-unknown-enum-values-as-null: true

  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB
      file-size-threshold: 100MB
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  ai:
    openai:
      api-key: open_api_key
naver:
  clova:
    api-key: clova_api_key
api:
  userdetails:
    implementation: counselorUserDetailsService

stt:
  file:
    path:
      origin: /data/stt/audio/origin/
      convert: /data/stt/audio/convert/

ffmpeg:
  path: /usr/local/bin/ffmpeg

tus:
  uploadPath: /data/tus/upload/
  extension: ".webm"
  mergePath: /data/stt/audio/origin/
  pathPrefix: /api/v1/tus

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
security:
  permit-all-urls:
    - "/user/**"
    - "/*/counselor/signup"
    - "/*/counselor/login"
    - "/swagger-ui/**"
    - "/*/api-docs/**"
    - "/swagger-ui.html"
    - "/h2-console/**"
    - "/actuator/health"
    - "/*/test/sentry/**"
keycloak:
  url: https://caringnote.co.kr/keycloak/
  admin-username: cnAdmin
  admin-password: caringNote@2024
  realm: caringnote

management:
  endpoints:
    web:
      exposure:
        include: health

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${spring.profiles.active}
  traces-sample-rate: 0.1
  send-default-pii: false