name: CI/CD Pipeline (Staging)

on:
  push:
    branches:
      - develop # develop 브랜치 트리거
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v2

      - name: Kakao Cloud Container Registry 로그인
        uses: docker/login-action@v2
        with:
          registry: medi-bird.kr-central-2.kcr.dev
          username: ${{ secrets.KCR_ACCESS_KEY_ID }}
          password: ${{ secrets.KCR_SECRET_KEY }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            medi-bird.kr-central-2.kcr.dev/cn-api-stage/cn-api-stage:latest
            medi-bird.kr-central-2.kcr.dev/cn-api-stage/cn-api-stage:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: VM에 배포 (Staging)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            # staging 디플로이먼트를 대상으로 변경하고 github.sha 태그 사용
            kubectl set image deployment/caring-note-api caring-note-api=medi-bird.kr-central-2.kcr.dev/cn-api-stage/cn-api-stage:${{ github.sha }} -n caring-note-staging

            kubectl annotate deployment/caring-note-api kubernetes.io/change-cause="이미지 업데이트: ${{ github.sha }}" -n caring-note-staging